### ISSUE TITLE
自定义滚动条样式

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#16]
```css
div::-webkit-scrollbar {
    width: 6px; /* 高宽分别对应横竖滚动条的尺寸 */
    height: 1px;
}
/* 滚动条里面小方块 */
div::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background: #999;
}
/* 滚动条里面轨道 */
div::-webkit-scrollbar-track {
    border-radius: 4px;
    background: #f2f2f2;
}
```
