### ISSUE TITLE
iPhoneX中的安全区域全覆盖

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#17]
iPhoneX中的安全区域全覆盖，在 meta 标签中添加 viewport-fit=cover

	<meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">

	auto：  默认 viewprot-fit:contain; 页面内容显示在 safe area 内
 	cover： viewport-fit:cover,页面内容充满屏幕

 	当我们设置 viewport-fit:cover 时：设置如下
    ```css
	body {
	    padding-top: constant(safe-area-inset-top);   /* 为导航栏+状态栏的高度 88px */          
	    padding-left: constant(safe-area-inset-left);   /* 如果未竖屏时为0 */               
	    padding-right: constant(safe-area-inset-right); /* 如果未竖屏时为0 */              
	    padding-bottom: constant(safe-area-inset-bottom);/* 为底下圆弧的高度 34px */      
	}
    ```
