### ISSUE TITLE
修改 placeholder 颜色

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#18]
```css
input::-webkit-input-placeholder,
textarea::-webkit-input-placeholder {
    color: #999;
}

input:-moz-placeholder,
textarea:-moz-placeholder {
    color: #999;
}

input::-moz-placeholder,
textarea::-moz-placeholder {
    color: #999;
}

input:-ms-input-placeholder,
textarea:-ms-input-placeholder {
    color: #999;
}
```
