### ISSUE TITLE
元素水平垂直居中对齐

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#22]
### 方式一 `absolute && translate`
    ```css
    .parent {
        position: relative;
    }
    .targetElm {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    ```

### 方式二 `absolute`
    ```css
    .parent {
        position: relative;
    }
    .targetElm {
        position: absolute;
        margin: auto;
        width: 100px;
        height: 50px;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
    }
    ```

### 方式三 `table && table-cell`
    ```css
    .parent {
        display: table;
        width: 100%;
        height: 50px;
    }
    .son {
        display: table-cell;
        vertical-align: middle;
    }
    ```

### 方式四
    ```css
    .parent {
        display: flex;
    } 
    .son {
        margin: auto;
    }
    ```

    或
    ```css
    .parent {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    ```

    或
    ```css
    .parent {
        display: flex;
        justify-content: center;
    }
    .son {
        align-self: center;
    }
    ```
