### ISSUE TITLE
div 包裹 img 不做任务设置的情况下img与div下面有白边

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#26]
```html
<div>
    <img src="./img.jpg" width="100%" height="100%" />
</div>
```

```css
div, img {
    margin: 0;
    padding: 0;
}
div {
    width: 100%
}
```

* 方法一
```css
div {
    height: 250px;
}
```

* 方法二
```css
div {
    font-size: 0;
}
```

* 方法三
```css
div {
    line-height: 0;
}
```

* 方法四
```css
img {
    display: block;
}
```
