### ISSUE TITLE
50.移动端 Retina 屏幕 1px 的解决方案

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#50]
1. 伪类选择器结合 `transform`: `scale` 缩小一半;

2. `viewport` 结合 `rem`

```html
<!-- devicePixelRatio=2 -->
<meta name="viewport" content="initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no">

<!-- devicePixelRatio=3 -->
<meta name="viewport" content="initial-scale=0.3333333333333333, maximum-scale=0.3333333333333333, minimum-scale=0.3333333333333333, user-scalable=no">
```

3. 使用 `background-image`

```css
.background-image-1px {
    background: url(../img/line.png) repeat-x left bottom;
    -webkit-background-size: 100% 1px;
    background-size: 100% 1px;
}
```

4. 使用 `border-image`

```css
.border-image-1px {
    border-bottom: 1px solid #666;
}
@media only screen and (-webkit-min-device-pixel-ratio: 2) {
    .border-image-1px {
        border-bottom: none;
        border-width: 0 0 1px 0;
        -webkit-border-image: url(../img/linenew.png) 0 0 2 0 stretch;
        border-image: url(../img/linenew.png) 0 0 2 0 stretch;
    }
}
```
