### ISSUE TITLE
70:清除浮动元素对父元素的影响

### ISSUE THREAD

**Issue by wqjiao** [wqjiao/Points-Issues#70]
1. 针对父元素增加伪类
```css
  .clearfix::after,
  .clearfix::before{
      content: "";
      display: block;
      clear: both;
      height:0;
      line-height: 0;
      visibility: hidden;
  }
```
